apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: bond0-vlan32
spec:
  desiredState:
    interfaces:
      - name: bond0.32
        type: vlan
        state: up
        vlan:
          base-iface: bond0
          id: 32
        ipv4:
          enabled: false
        ipv6:
          enabled: false
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: live-migration-nad
  namespace: openshift-cnv
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "live-migration-bridge",
      "type": "macvlan",
      "master": "bond0.32",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "range": "10.32.0.0/24",
        "exclude": [ "10.32.0.0/29" ]
      }
    }


# oc edit hyperconverged kubevirt-hyperconverged -n openshift-cnv
# spec:liveMigrationConfig:network: live-migration-nad