apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: single-eth-vlan
spec:
  nodeSelector:
    kubernetes.io/hostname: <hostname>
  desiredState:
    interfaces:
      - name: <devicename>
        type: ethernet
        state: up
        mac-address: <macaddress>
        ipv4:
          enabled: false
        ipv6:
          enabled: false
      - name: vlan<vlanid>
        type: vlan
        state: up
        vlan:
          base-iface: <devicename>
          id: <vlanid>
        ipv4:
          enabled: true
          address:
            - ip: <ipaddress>
              prefix-length: <netmask>
          dhcp: false
        ipv6:
          enabled: false