apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br-trunk-nncp
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  desiredState:
    interfaces:
      - name: br-trunk
        type: ovs-bridge
        state: up
        bridge:
          allow-extra-patch-ports: true
          options:
            stp: false # DO NOT ENABLE STP UNLESS YOU KNOW WHAT YOU ARE DOING
          port:
            - name: bond0
    ovn:
      bridge-mappings:
        - bridge: br-trunk
          localnet: localnet-trunk
          state: present
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan4
  namespace: vlan4-test
spec:
  config: |-
    {
        "cniVersion": "0.4.0",
        "name": "localnet-trunk",
        "type": "ovn-k8s-cni-overlay",
        "netAttachDefName": "vlan4-test/vlan4",
        "topology": "localnet",
        "vlanID": 4
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: vlan4-annotation-debug-91
  namespace: vlan4-test
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        { "name": "vlan4", "ips": ["10.4.0.91/24"], "gateway": "10.4.0.1" }
      ]
spec:
  containers:
    - name: tools
      image: quay.io/openshift/origin-tools:4.19
      command: ["sleep", "infinity"]
      securityContext:
        runAsUser: 0
---
apiVersion: v1
kind: Pod
metadata:
  name: vlan4-annotation-debug-92
  namespace: vlan4-test
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        { "name": "vlan4", "ips": ["10.4.0.92/24"], "gateway": "10.4.0.1" }
      ]
spec:
  containers:
    - name: tools
      image: quay.io/openshift/origin-tools:4.19
      command: ["sleep", "infinity"]
      securityContext:
        runAsUser: 0