###
# This is a setup that allows testing of a VLAN interface
# oc debug node/ocp1
# oc rsh vlan4-debug
###
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: bond0-vlan4
spec:
  desiredState:
    interfaces:
      - name: bond0.4
        type: vlan
        state: up
        vlan:
          base-iface: bond0
          id: 4
        ipv4:
          enabled: false
        ipv6:
          enabled: false
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan4-macvlan-whereabouts
  namespace: default
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "bond0.4",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "ranges": [
          {
            "subnet": "10.4.0.0/24",
            "rangeStart": "10.4.0.50",
            "rangeEnd":   "10.4.0.200"
          }
        ],
        "gateway": "10.4.0.1",
        "routes": [
          { "dst": "0.0.0.0/0", "gw": "10.4.0.1" }
        ],
        "dns": {
          "nameservers": ["10.3.0.3", "9.9.9.9"]
        },
        "exclude": [
          "10.4.0.1/32",     
          "10.4.0.2/31",     
          "10.4.0.240/28"   
        ]
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: vlan4-annotation-debug-91
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        { "name": "vlan4-macvlan-whereabouts", "ips": ["10.4.0.91/24"] }
      ]
spec:
  containers:
    - name: tools
      image: quay.io/openshift/origin-tools:4.19
      command: ["sleep", "infinity"]
      securityContext:
        runAsUser: 0