apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    vm.kubevirt.io/validations: |
      [
        {
          "name": "minimal-required-memory",
          "path": "jsonpath::.spec.domain.memory.guest",
          "rule": "integer",
          "message": "This VM requires more memory.",
          "min": 1610612736
        }
      ]
  labels:
    app: rhel9-cudn-example
    kubevirt.io/dynamic-credentials-support: 'true'
    vm.kubevirt.io/template: rhel9-server-small
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.34.0
  name: rhel9-cudn-example
  namespace: project1
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        creationTimestamp: null
        name: rhel9-cudn-example
      spec:
        sourceRef:
          kind: DataSource
          name: rhel9
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  runStrategy: Halted
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: rhel9
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: rhel9-cudn-example
        kubevirt.io/size: small
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - macAddress: '02:85:38:00:00:0a'
              masquerade: {}
              model: virtio
              name: default
            - bridge: {}
              macAddress: '02:85:38:00:00:0b'
              model: virtio
              name: nic-vlan37
              state: up
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel9.6.0
        memory:
          guest: 2Gi
        resources: {}
      networks:
        - name: default
          pod: {}
        - multus:
            networkName: vlan37
          name: nic-vlan37
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: rhel9-cudn-example
          name: rootdisk
        - cloudInitNoCloud:
            networkData: |
              version: 2
              ethernets:
                eth1:
                  dhcp4: no
                  addresses:
                    - 10.37.0.50/24
                  gateway4: 10.37.0.1
                  nameservers:
                    addresses:
                      - 10.3.0.3
                      - 9.9.9.9
                  dhcp6: no
                  accept-ra: false
            userData: |
              #cloud-config
              user: cloud-user
              password: Pass123!
              chpasswd:
                expire: false
          name: cloudinitdisk
