apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: ocp
rendezvousIP: 10.1.0.11
hosts:
  - hostname: cp1 # Control Plane 1
    role: master
    interfaces:
      - name: eno1
        macAddress: A1:B2:3C:4D:5E:11
    rootDeviceHints:
      deviceName: "/dev/sda"
    networkConfig:
      interfaces:
        - name: eno1
          type: ethernet
          state: up
          mac-address: A1:B2:3C:4D:5E:11
          ipv4:
            enabled: true
            address:
              - ip: 10.1.0.11
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 10.1.0.2
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.1.0.1
            next-hop-interface: eno1
            table-id: 254
  - hostname: cp2 # Control Plane 2
    role: master
    interfaces:
      - name: eno1
        macAddress: A1:B2:3C:4D:5E:12
    rootDeviceHints:
      deviceName: "/dev/sda"
    networkConfig:
      interfaces:
        - name: eno1
          type: ethernet
          state: up
          mac-address: A1:B2:3C:4D:5E:12
          ipv4:
            enabled: true
            address:
              - ip: 10.1.0.12
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 10.1.0.2
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.1.0.1
            next-hop-interface: eno1
            table-id: 254
  - hostname: cp3 # Control Plane 3
    role: master
    interfaces:
      - name: eno1
        macAddress: A1:B2:3C:4D:5E:13
    rootDeviceHints:
      deviceName: "/dev/sda"
    networkConfig:
      interfaces:
        - name: eno1
          type: ethernet
          state: up
          mac-address: A1:B2:3C:4D:5E:13
          ipv4:
            enabled: true
            address:
              - ip: 10.1.0.13
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 10.1.0.2
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.1.0.1
            next-hop-interface: eno1
            table-id: 254