apiVersion: v1
baseDomain: ocp.example.com
metadata:
  name: cluster1
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.1.0.0/24
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  baremetal:
    apiVIP: 10.1.0.9
    ingressVIP: 10.1.0.10
pullSecret: '<hidden>'
sshKey: '<hidden> THIS IS THE PUBLIC KEY'
#proxy:
#  httpProxy: http://user:password@proxy.example.com:3128
#  httpsProxy: http://user:password@proxy.example.com:3128
#  noProxy: ocp.example.com,10.1.0.0/24,10.128.0.0/14,172.30.0.0/16,api-int.ocp.example.com,*.ocp.example.com